### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LVarsaminov**
I've added information on how to start the app.

### CODE REVIEW

**Comment by clangelov** [comment]
you are missing the solution for not being able to resolve the nuget packages 
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	NU1100	Unable to resolve 'Microsoft.EntityFrameworkCore (>= 8.0.3)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not considered: Microsoft Visual Studio Offline Packages, nuget.org.	SportsGoods.Core	C:\Projects\SportsGoods\SportsGoods.Core\SportsGoods.Core.csproj	1

**Comment by LVarsaminov** [comment]
Updated the README.md by providing a solution for resolving the nuget packages.

**Comment by clangelov** [comment]
it's fine

**Review by clangelov — COMMENTED** [review]
it's fine

**Review by clangelov — COMMENTED** [review]
.

**Review by clangelov — APPROVED** [review]

**Pull request merged**
